### ISSUE TITLE
Change type of properties argument in CreateSubDevices method

### ISSUE THREAD

**Issue by mikhail-khalizev** [lecode-official/opencl-dotnet#1]
https://github.com/lecode-official/opencl-dotnet/blob/6903150fa273799af731b75cb52dc6052cea6aee/OpenCl.DotNetCore.Interop/Devices/DevicesNativeApi.cs#L122

Hi. `properties` is input array of IntPtr, so should be:

            [In] [MarshalAs(UnmanagedType.LPArray)] IntPtr[] properties,

**Comment by lecode-official** [comment]
Hi Mikhail,

you are absolutely right. I have just pushed a fix (commit e2176d71552e0a17999b5e34f5795dd3dd182867). Thank you very much for your contribution.

David
